spring:
  application:
    name: NoticeBoard
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/notice_board?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: P@ssw0rd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        characterEncoding: UTF-8
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
